---
name: "HeaderAuth"
guid: "df78a0dc-a52a-4a9b-bae4-3f60390b83c4"
version: "1"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Jellyfin plugin for header based authentication"
description: >
  This plugin authenticates users based on a given http header value.

category: "Authentication"
owner: "NolanWelser"
artifacts:
  - "Jellyfin.Plugin.HeaderAuth.dll"
changelog: >
  changelog

